### PR TITLE
Database Query ( compatible with mysql, postgres, sqlite3)

### PR DESCRIPTION
**Pull request by Ganitagya**

### CODE REVIEW

**Comment by Ganitagya** [comment]
oh... of course 
I thought it to be a good idea to include all types of sql providers in one single activity.
But I understand the notion of Flogo being light weighted.
Will do the required modification.

@retgits  Will it be a good idea to keep all the CRUD methods in one activity ?
Like one activity having select, insert , delete queries ?

**Comment by retgits** [comment]
I would do separate activities as that would likely make your code easier.

**Comment by Ganitagya** [comment]
okay

**Comment by mellistibco** [comment]
Just to clarify, 3 activities, each activity with their own set of crud operations.

Also, we'll look into exposing a contribution model for activities, so that you could perhaps have an activity like this, but the cli will only import the specified packages corresponding to the specified sql driver typ.

**Comment by Ganitagya** [comment]
@mellistibco exactly my point "each activity with their own set of crud operations"
Like having an activity for each sql provider which can perform all crud operations.
So 3 activities in all and no unwanted imports.

I didnt understand this though : "exposing a contribution model for activities, so that you could perhaps have an activity like this, but the cli will only import the specified packages corresponding to the specified sql driver type"

**Comment by mellistibco** [comment]
@Ganitagya cool. The idea is more or less around a future enhancement that would allow a single activity like this one in the future, but the binary would only include the required deps. For now, not an issue :)

**Comment by Ganitagya** [comment]
:+1:

**Pull request merged**
